import { Pieces } from "@/app/components/Piece"

type PieceConfig = {
    position: string,
    piece: JSX.Element
}

type BoardConfig = {
    WhiteQueen: PieceConfig,
    WhiteKing: PieceConfig,
    WhiteRookA: PieceConfig,
    WhiteRookH: PieceConfig,
    WhiteKnightB: PieceConfig,
    WhiteKnightG: PieceConfig,
    WhiteBishopC: PieceConfig,
    WhiteBishopF: PieceConfig,
    WhitePawnA: PieceConfig,
    WhitePawnB: PieceConfig,
    WhitePawnC: PieceConfig,
    WhitePawnD: PieceConfig,
    WhitePawnE: PieceConfig,
    WhitePawnF: PieceConfig,
    WhitePawnG: PieceConfig,
    WhitePawnH: PieceConfig,
    BlackQueen: PieceConfig,
    BlackKing: PieceConfig,
    BlackRookA: PieceConfig,
    BlackRookH: PieceConfig,
    BlackKnightB: PieceConfig,
    BlackKnightG: PieceConfig,
    BlackBishopC: PieceConfig,
    BlackBishopF: PieceConfig,
    BlackPawnA: PieceConfig,
    BlackPawnB: PieceConfig,
    BlackPawnC: PieceConfig,
    BlackPawnD: PieceConfig,
    BlackPawnE: PieceConfig,
    BlackPawnF: PieceConfig,
    BlackPawnG: PieceConfig,
    BlackPawnH: PieceConfig
}

const StartingBoardConfig: BoardConfig = {
    WhiteQueen: { position: "d1", piece: Pieces.WhiteQueen },
    WhiteKing: { position: "e1", piece: Pieces.WhiteKing },
    WhiteRookA: { position: "a1", piece: Pieces.WhiteRook },
    WhiteRookH: { position: "h1", piece: Pieces.WhiteRook },
    WhiteKnightB: { position: "b1", piece: Pieces.WhiteKnight },
    WhiteKnightG: { position: "g1", piece: Pieces.WhiteKnight },
    WhiteBishopC: { position: "c1", piece: Pieces.WhiteBishop },
    WhiteBishopF: { position: "f1", piece: Pieces.WhiteBishop },
    WhitePawnA: { position: "a2", piece: Pieces.WhitePawn },
    WhitePawnB: { position: "b2", piece: Pieces.WhitePawn },
    WhitePawnC: { position: "c2", piece: Pieces.WhitePawn },
    WhitePawnD: { position: "d2", piece: Pieces.WhitePawn },
    WhitePawnE: { position: "e2", piece: Pieces.WhitePawn },
    WhitePawnF: { position: "f2", piece: Pieces.WhitePawn },
    WhitePawnG: { position: "g2", piece: Pieces.WhitePawn },
    WhitePawnH: { position: "h2", piece: Pieces.WhitePawn },
    BlackQueen: { position: "d1", piece: Pieces.BlackQueen },
    BlackKing: { position: "e1", piece: Pieces.BlackKing },
    BlackRookA: { position: "a1", piece: Pieces.BlackRook },
    BlackRookH: { position: "h1", piece: Pieces.BlackRook },
    BlackKnightB: { position: "b1", piece: Pieces.BlackKnight },
    BlackKnightG: { position: "g1", piece: Pieces.BlackKnight },
    BlackBishopC: { position: "c1", piece: Pieces.BlackBishop },
    BlackBishopF: { position: "f1", piece: Pieces.BlackBishop },
    BlackPawnA: { position: "a2", piece: Pieces.BlackPawn },
    BlackPawnB: { position: "b2", piece: Pieces.BlackPawn },
    BlackPawnC: { position: "c2", piece: Pieces.BlackPawn },
    BlackPawnD: { position: "d2", piece: Pieces.BlackPawn },
    BlackPawnE: { position: "e2", piece: Pieces.BlackPawn },
    BlackPawnF: { position: "f2", piece: Pieces.BlackPawn },
    BlackPawnG: { position: "g2", piece: Pieces.BlackPawn },
    BlackPawnH: { position: "h2", piece: Pieces.BlackPawn },
}